'
' ------------------------------------------------------------------------
' MULTIPLE CALLBACK UNDER RAPIDQ    CallBackAll.Inc             by Jacques
'
' Includes all the CallBack
'
' August 13th, 2006
' ------------------------------------------------------------------------


$DEFINE __RQCALLBACKS

'
$IFNDEF _CALLBACK_0
$Include "includes\CallBack_0.Inc"
$ENDIF

$IFNDEF _CALLBACK_1
$Include "includes\CallBack_1.Inc"
$ENDIF

$IFNDEF _CALLBACK_2
$Include "includes\CallBack_2.Inc"
$ENDIF

$IFNDEF _CALLBACK_3
$Include "includes\CallBack_3.Inc"
$ENDIF

$IFNDEF _CALLBACK_4
$Include "includes\CallBack_4.Inc"
$ENDIF
$IFNDEF _CALLBACK_5
$Include "includes\CallBack_5.Inc"
$ENDIF

$IFNDEF _CALLBACK_6
$Include "includes\CallBack_6.Inc"
$ENDIF

$IFNDEF _CALLBACK_7
$Include "includes\CallBack_7.Inc"
$ENDIF

$IFNDEF _CALLBACK_8
$Include "includes\CallBack_8.Inc"
$ENDIF



'





