sub settingsclick
select case indicatorslist.itemindex
case 0
ADR112cppform.visible=1
case 1
atrchannelform.visible=1
case 2
balance_point_fiboform.visible=1
case 3
bandsform.visible=1
case 4
bandscppform.visible=1
case 5
bbhlform.visible=1
case 6
bbhlcppform.visible=1
case 7
bowelsform.visible=1
case 8
cogform.visible=1
case 9
COG_of_RSTLform.visible=1
case 10
cogcppform.visible=1
case 11
Din_fibo_highform.visible=1
case 12
Elliot_Wave_3_Level_ZZ_Semaforform.visible=1
case 13
envelopform.visible=1
case 14
Ichimokuform.visible=1
case 15
jupiter_saturn_cycleform.visible=1
case 16
Levelsform.visible=1
case 17
maform.visible=1
case 18
MA_Chanels_FiboEnv_Midform.visible=1
case 19
Murrey_Mathform.visible=1
case 20
past_regression_deviatedform.visible=1
case 21
Planetary_linesform.visible=1
case 22
priceclose1440form.visible=1
case 23
RSTLform.visible=1
case 24
smafiboform.visible=1
case 25
Square_numbersform.visible=1
case 26
synodic_cycleform.visible=1
case 27
TMA_CGform.visible=1
case 28
TSFform.visible=1
case 29
vegascform.visible=1
case 30
VolatilityPivotform.visible=1
case 31
VolatilityStopform.visible=1
case 32
waterlevelcppform.visible=1
case 33
weeklypivotcppform.visible=1
case 34
zigzagform.visible=1
case 35
zigzagcppform.visible=1
case 36
ztrendine_slope_pi_ratioform.visible=1
case 37
Acceleratorform.visible=1
case 38
astro_retrogradeform.visible=1
case 39
atrform.visible=1
case 40
CandleAvgform.visible=1
case 41
CoronaSwingPositionform.visible=1
case 42
declination_systemform.visible=1
case 43
Ehlersfishertransformform.visible=1
case 44
energyform.visible=1
case 45
fftspectroform.visible=1
case 46
ForceIndexform.visible=1
case 47
Gauquelin_sectorform.visible=1
case 48
IVolumeform.visible=1
case 49
LSSform.visible=1
case 50
mfiform.visible=1
case 51
moon_scaleform.visible=1
case 52
planetary_speedform.visible=1
case 53
planets_scaleform.visible=1
case 54
pricecloseform.visible=1
case 55
RBCIform.visible=1
case 56
realMACDform.visible=1
case 57
rsiform.visible=1
case 58
smFisherTransform3nrform.visible=1
case 59
spectrometerform.visible=1
case 60
stepftvcprdlform.visible=1
case 61
steprsiform.visible=1
case 62
stochasticform.visible=1
case 63
threeD_Oscilatorform.visible=1
case 64
TSCDform.visible=1
case 65
valuechartform.visible=1
case 66
vcatrcform.visible=1
case 67
Weighted_WCCIform.visible=1
end select
end sub
