sub settingsclick
select case indicatorslist.itemindex
case 0
ADR112cppform.visible=1
case 1
atrchannelform.visible=1
case 2
balance_point_fiboform.visible=1
case 3
bandsform.visible=1
case 4
bandscppform.visible=1
case 5
bbhlform.visible=1
case 6
bbhlcppform.visible=1
case 7
bowelsform.visible=1
case 8
cogform.visible=1
case 9
COG_of_RSTLform.visible=1
case 10
cogcppform.visible=1
case 11
Din_fibo_highform.visible=1
case 12
envelopform.visible=1
case 13
jupiter_saturn_cycleform.visible=1
case 14
Levelsform.visible=1
case 15
maform.visible=1
case 16
MA_Chanels_FiboEnv_Midform.visible=1
case 17
Murrey_Mathform.visible=1
case 18
Planetary_linesform.visible=1
case 19
priceclose1440form.visible=1
case 20
RSTLform.visible=1
case 21
smafiboform.visible=1
case 22
synodic_cycleform.visible=1
case 23
TSFform.visible=1
case 24
vegascform.visible=1
case 25
VolatilityPivotform.visible=1
case 26
VolatilityStopform.visible=1
case 27
waterlevelcppform.visible=1
case 28
weeklypivotcppform.visible=1
case 29
zigzagform.visible=1
case 30
zigzagcppform.visible=1
case 31
ztrendine_slope_pi_ratioform.visible=1
case 32
Acceleratorform.visible=1
case 33
astro_retrogradeform.visible=1
case 34
atrform.visible=1
case 35
CandleAvgform.visible=1
case 36
CoronaSwingPositionform.visible=1
case 37
declination_systemform.visible=1
case 38
Ehlersfishertransformform.visible=1
case 39
energyform.visible=1
case 40
fftspectroform.visible=1
case 41
ForceIndexform.visible=1
case 42
Gauquelin_sectorform.visible=1
case 43
IVolumeform.visible=1
case 44
LSSform.visible=1
case 45
mfiform.visible=1
case 46
planetary_speedform.visible=1
case 47
planets_scaleform.visible=1
case 48
pricecloseform.visible=1
case 49
rsiform.visible=1
case 50
smFisherTransform3nrform.visible=1
case 51
spectrometerform.visible=1
case 52
stepftvcprdlform.visible=1
case 53
steprsiform.visible=1
case 54
threeD_Oscilatorform.visible=1
case 55
valuechartform.visible=1
case 56
vcatrcform.visible=1
end select
end sub
