sub settingsclick
select case indicatorslist.itemindex
case 0
ADR112cppform.visible=1
case 1
atrchannelform.visible=1
case 2
balance_point_fiboform.visible=1
case 3
bandsform.visible=1
case 4
bandscppform.visible=1
case 5
bbhlform.visible=1
case 6
bbhlcppform.visible=1
case 7
bowelsform.visible=1
case 8
cogform.visible=1
case 9
COG_of_RSTLform.visible=1
case 10
cogcppform.visible=1
case 11
Din_fibo_highform.visible=1
case 12
Elliot_Wave_3_Level_ZZ_Semaforform.visible=1
case 13
envelopform.visible=1
case 14
Ichimokuform.visible=1
case 15
jupiter_saturn_cycleform.visible=1
case 16
Levelsform.visible=1
case 17
maform.visible=1
case 18
MA_Chanels_FiboEnv_Midform.visible=1
case 19
Murrey_Mathform.visible=1
case 20
past_regression_deviatedform.visible=1
case 21
Planetary_linesform.visible=1
case 22
planetsqnform.visible=1
case 23
priceclose1440form.visible=1
case 24
RSTLform.visible=1
case 25
smafiboform.visible=1
case 26
Square_numbersform.visible=1
case 27
synodic_cycleform.visible=1
case 28
TMA_CGform.visible=1
case 29
TSFform.visible=1
case 30
vegascform.visible=1
case 31
VolatilityPivotform.visible=1
case 32
VolatilityStopform.visible=1
case 33
waterlevelcppform.visible=1
case 34
weeklypivotcppform.visible=1
case 35
zigzagform.visible=1
case 36
zigzagcppform.visible=1
case 37
ztrendine_slope_pi_ratioform.visible=1
case 38
Acceleratorform.visible=1
case 39
astro_retrogradeform.visible=1
case 40
atrform.visible=1
case 41
CandleAvgform.visible=1
case 42
CoronaSwingPositionform.visible=1
case 43
declination_systemform.visible=1
case 44
Ehlersfishertransformform.visible=1
case 45
energyform.visible=1
case 46
fftspectroform.visible=1
case 47
ForceIndexform.visible=1
case 48
Gauquelin_sectorform.visible=1
case 49
IVolumeform.visible=1
case 50
LSSform.visible=1
case 51
mfiform.visible=1
case 52
moon_scaleform.visible=1
case 53
planetary_speedform.visible=1
case 54
planets_scaleform.visible=1
case 55
pricecloseform.visible=1
case 56
RBCIform.visible=1
case 57
realMACDform.visible=1
case 58
rsiform.visible=1
case 59
smFisherTransform3nrform.visible=1
case 60
spectrometerform.visible=1
case 61
stepftvcprdlform.visible=1
case 62
steprsiform.visible=1
case 63
stochasticform.visible=1
case 64
threeD_Oscilatorform.visible=1
case 65
TSCDform.visible=1
case 66
valuechartform.visible=1
case 67
vcatrcform.visible=1
case 68
Weighted_WCCIform.visible=1
end select
end sub
