#define topic1 0
#define topic2 0
#define topic3 0
#define datasource 0
#define importcsv 0
#define exportcsv 0
#define attributetimeframe 0
#define toolsettings 0
#define showseparatecanvas 0
#define objectslist 0
#define astrowheelsettings 0
#define chartopening 0
#define linestudies 0
#define averagerangeadr 0
#define atrchannel 0
#define bollingerbands 0
#define bbhl 0
#define bowels 0
#define centerofgravity 0
#define cogofrstl 0
#define dinfibohigh 0
#define enveloppes 0
#define levels 0
#define simplemovingaverage 0
#define machanelsfiboenvmid 0
#define murreymath 0
#define planetarylines 0
#define fibomachannels 0
#define vegas 0
#define rstl 0
#define timeseriesforecast 0
#define volatilitypivot 0
#define volatilitystop 0
#define waterlevel 0
#define weeklypivot 0
#define zigzag 0
#define accelerator 0
#define astroretrograde 0
#define atr 0
#define candleaverage 0
#define declinationsystem 0
#define ehlersfishertransform 0
#define fftspectro 0
#define forceindex 0
#define gauquelinsector 0
#define lss 0
#define moneyflowindex 0
#define planetscale 0
#define rsi 0
#define smfishertransform3nr 0
#define spectrometer 0
#define stepftvcprdl 0
#define steprsi 0
#define threedoscilator 0
#define valuechart 0
#define valuechartofatrchannels 0
#define howtocreateanewindicator 0
#define howtousemultitimeframeindicators 0
#define theselectiontool 0
#define indicators 0
#define about 0
#define displayedfile 0
#define chartbars 0
#define charttf 0
#define importedfile 0
#define openedfilesnb 0
#define rowgridoffset 0
#define grid 0
#define date 0
#define time 0
#define open 0
#define high 0
#define low 0
#define close 0
#define volume 0
#define date1 0
#define time1 0
#define open1 0
#define high1 0
#define low1 0
#define close1 0
#define volume1 0
#define numbars 0
#define bars 0
#define graphvhigh 0
#define graphvlow 0
#define alltimehigh 0
#define alltimelow 0
#define btnonclickdrawbox 0
#define reimportfile 0
#define opena 0
#define highta 0
#define lowa 0
#define closea 0
#define datea 0
#define timea 0
#define volumea 0
#define constants 0
#define ibarshift 0
#define ihighest 0
#define ilowest 0
#define timeb 0
#define itimeb 0
#define timeminute 0
#define timehour 0
#define timedayofweek 0
#define mathmax 0
#define mathmin 0
#define idate 0
#define itime 0
#define iopen 0
#define ihigh 0
#define ilow 0
#define iclose 0
#define ivolume 0
#define aboutqtgen 0
#define aboutqtguard 0
#define gettingstarted 0

